development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:8ded2e27e00dc3e50e40a5cdb3eae4e2@soldierfish.redistogo.com:11922/
#   channel_prefix: slim_production
# production: &production
#   adapter: redis
#   url: redis://10.10.3.153:6381
# development: &development
#   adapter: redis
#   url: redis://localhost:6379
# test: *development
